### ISSUE TITLE
Size of images in the technologies section are uneavenly sized

### ISSUE THREAD

**Issue by redomar** [redomar/frontend-redomar#1]
The images from the different services the website uses are different heights which do not render well; i.e Jenkins is huge, while docker is half the size in height.

![image](https://app.gitkraken.com/api/glo/boards/5dba32117e8495000f040112/attachments/5dbb3874917173000f2ea6ef)

**Comment by samsonyuwono** [comment]
@redomar, I'll take on this issue

**Comment by redomar** [comment]
Thanks for the help 👍. Worked like a charm.
